# -*- coding: utf-8 -*-
"""bill_division

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IE0NlfGZrAtviPEg0UVltYWDZlwjjgeC
"""

#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'bonAppetit' function below.
#
# The function accepts following parameters:
#  1. INTEGER_ARRAY bill
#  2. INTEGER k
#  3. INTEGER b
#
def bonAppetit(bill, k, b):
    total_cost = sum(bill)  # Calculate the total cost of the meal
    anna_share = (total_cost - bill[k]) // 2  # Anna's fair share excluding the item she didn't eat

    if b == anna_share:
        print("Bon Appetit")  # If charged correctly
    else:
        print(b - anna_share)  # Print the amount overcharged


if __name__ == '__main__':
    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    k = int(first_multiple_input[1])

    bill = list(map(int, input().rstrip().split()))

    b = int(input().strip())

    bonAppetit(bill, k, b)