# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10sblWSzEF_JCou58M2gpLHHpXFkWLG5V
"""

#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'birthdayCakeCandles' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY candles as parameter.
#

def birthdayCakeCandles(arr):
    # Write your code here
    n=len(arr)
    maximum = 0
    count = 0
    for i in range(n):
            if arr[i]>maximum:
                maximum = arr[i]
                count = 1
            elif arr[i]==maximum:
                count += 1
    # Write your code heretrip().split()))
    return count

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    candles_count = int(input().strip())

    candles = list(map(int, input().rstrip().split()))

    result = birthdayCakeCandles(candles)

    fptr.write(str(result) + '\n')

    fptr.close()