# -*- coding: utf-8 -*-
"""comparing_triplet_Problem_solving.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cWTzD3lRWPUQjYvnWplqcN10kTsooJrY
"""

def compareTriplets(a, b):
    # Initialize scores
    alice_score = 0
    bob_score = 0

    # Compare each category (i.e., each index in the triplet)
    for i in range(3):
        if a[i] > b[i]:
            alice_score += 1
        elif a[i] < b[i]:
            bob_score += 1

    # Return the comparison points as a list
    return [alice_score, bob_score]

# Read input from stdin
a = list(map(int, input().split()))
b = list(map(int, input().split()))

# Call the function and print the result
result = compareTriplets(a, b)
print(" ".join(map(str, result)))