# -*- coding: utf-8 -*-
"""plusminus_problemsolving.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UGM3VuJE5cvvuDfcpClmXcAMMYFc56U7
"""

#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    pos = neg = zero = 0
    for i in range(n):
        if arr[i]>0:
            pos+=1
        elif arr[i]<0:
            neg+=1
        else:
            zero+=1
    print(pos/n)
    print(neg/n)
    print(zero/n)
    # Write your code here
if __name__ == '__main__':
    arr = list(map(int, input().rstrip().split()))
    # Read the entire array in a single line and convert elements to integers

    plusMinus(arr) # Call the function with the array