# -*- coding: utf-8 -*-
"""sock_marchent_problem_solving.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HLjqfgypoN8thnY2S8qMeBjQaxLdR2gL
"""

#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'sockMerchant' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY ar
#

def sockMerchant(n, ar):
    # Write your code here
    count=0
    d= {}

    for i in ar:
        d[i]=d.get(i,0)+1

    for i in d.keys():
        count +=d[i]//2
    return count

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    ar = list(map(int, input().rstrip().split()))

    result = sockMerchant(n, ar)

    fptr.write(str(result) + '\n')

    fptr.close()